In [ ]:
!wget https://raw.githubusercontent.com/DING-1994/llm2023/main/icat.txt

--2024-05-09 04:21:53--  https://raw.githubusercontent.com/DING-1994/llm2023/main/icat.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31611 (31K) [text/plain]
Saving to: ‘icat.txt’

icat.txt            100%[===================>]  30.87K  --.-KB/s    in 0.002s  

2024-05-09 04:21:53 (12.8 MB/s) - ‘icat.txt’ saved [31611/31611]



In [ ]:
# read it in to inspect it
with open('icat.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(text[:100])

吾輩は猫である。名前はまだ無い。
　どこで生れたかとんと見当《けんとう》がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかも


In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  10553


In [ ]:
# let's look at the first 100 characters
print(text[:100])

吾輩は猫である。名前はまだ無い。
　どこで生れたかとんと見当《けんとう》がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかも


In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


―　、。々《》「」あいうえおかがきぎくぐけげこごさざしじすずせぜそぞただちっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろわをんァアイオカサシジスゼタッデトドニフブペマャヤリルレワンヴ・ー一丈三上下不世両並中丸主乗乱予事二云五交亭人今仕他付代以件任会伸佇低住体何余作例供侮便俳倍倒候偉側偸傍催像儀儘儲元兄先光入全具内円再写冷凝処出分切初判別利到刺刻前割剿力加助勇勉動勝勢勤包化匹十午卑原去友双反取受口句叩台合同名吐向君否含吶吸吹吾呈呑味呼咽問善喉喊喝喟喰嗅嘆嘲器四困国園地坐坪垂垣執報場増墻壁壊声壱変外多夜大天太失奇奥奪女奴好妙始姿嫌子存学守完宗定実室害家容宿寒寝察対射尊小少尻屁居屈屋層崩左己師帯帰常幅平年広床底度座庭廓廻弁弓引弟弱張強弾当形彩彼待後得御徳徴心必忍忘快念怒思急性恐息悟悪悲情惜想意愚愛感慢慨憤憶懐我或戦所手打投折抛抱押拶持指挨挫捕掃掌掠接掻揄描提揚揶撚敗教敬数敷文斎斑断斯新方族日早昂明易昔星春昼時景智暖暗暮暴更書最月有服望朝木末本杉来板枚果枝枯架柄柔栄校根格案桐梧棄棒椽業極楽構槌様権横樹機櫃欠次正歩死残段母毎毒比毛毫気水永池決波泣泥洒活流浩涎涙淡減渡渾満溌溝滅漆漫濁瀟火灰炎炬点烈焔無然煙煮熱燃燵爪片物犬猟猫猶獣獰玉王珀珍現理琥甘生産用由画畜畠番畳疋疑痛痞瘠癖癪発白百的皮盛盟目盲直相真眠眸眺眼着睡睨知矮石破碌磨神禁禽程種稼穏穴突窃窘窟立竹笑第笹筆等筋答箆節籠粋約純紙細終経結給絵総線縁繰缶置罵美義翌習考者耳聞聴職肉肝肥育胃胆背胡胸腕腹膏膚膝臍臓自臭至良色若苦英茂茶草菊華落葉蔑蔭薄薬藁行表衾袋装裏褐西要見規覗覚親観解言記訪訳訴詐評試詩話誘語読誰課調談論謡謹識議護豊買賞質走起越足路跳身車軍転軽較載輝輩輪辛辰辺込迎近返迫述追退送逅逆透這通速造逢遇運遍過道達違遠遥遭邂邸郎部酷醒采重野量金銭鏡鑑長開間関降限除険陽随隙際障隠隣雑雨震露静非面音頃頓頭頸頼額顔願顫風飛食飯飲飾養餓首馬馳駄騒験驚骨髭魔魚鰡鳴鴉鹿黄黒鼓鼠鼻鼾＃？［］｜
843


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
#print("stoi",stoi)
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("吾"))
print(decode(encode("吾")))
print(encode("吾輩"))
print(decode(encode("吾輩")))

[234]
吾
[234, 731]
吾輩


In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long) #encoding the entire text
print(data.shape, data.dtype)
print(data[:100]) # the 100 characters we looked at earier will to the GPT look like this

torch.Size([10553]) torch.int64
tensor([234, 731,  50, 534,  42,  10,  78,   4, 225, 194,  50,  65,  36, 522,
         11,   4,   0,   2,  44,  23,  42, 546,  79,  35,  15,  43,  83,  43,
        683, 340,   6,  21,  83,  43,  12,   7,  16,  39,  15,  47,   4, 150,
         42,  69, 671, 431,  11,  28,  68,  28,  68,  27,  35, 380,  42,  99,
        104, 113,  99, 104, 113, 495,  11,  41,  11,  35, 129,  36,  21,  50,
        691, 375,  27,  41,  11,  78,   4, 234, 731,  50,  23,  23,  42, 284,
         68,  41, 135, 779,  43,  11,  12,  69,  49,  82, 683,  35,   4,  27,
         15,  69])


In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
print("train_data[:block_size+1]",train_data[:block_size+1])# ths first "block_size" elements

train_data[:block_size+1] tensor([234, 731,  50, 534,  42,  10,  78,   4, 225])


In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([234]) the target: 731
when input is tensor([234, 731]) the target: 50
when input is tensor([234, 731,  50]) the target: 534
when input is tensor([234, 731,  50, 534]) the target: 42
when input is tensor([234, 731,  50, 534,  42]) the target: 10
when input is tensor([234, 731,  50, 534,  42,  10]) the target: 78
when input is tensor([234, 731,  50, 534,  42,  10,  78]) the target: 4
when input is tensor([234, 731,  50, 534,  42,  10,  78,   4]) the target: 225


In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = decode(torch.Tensor.tolist(x[:t+1]))
    target = decode([int(y[t])])
    print(f"when input is {context} the target: {target}")

when input is 吾 the target: 輩
when input is 吾輩 the target: は
when input is 吾輩は the target: 猫
when input is 吾輩は猫 the target: で
when input is 吾輩は猫で the target: あ
when input is 吾輩は猫であ the target: る
when input is 吾輩は猫である the target: 。
when input is 吾輩は猫である。 the target: 名


In [ ]:
torch.manual_seed(137)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) #tensor([ 611, 7648, 3056, 3583]) the start index for each block
    print("ix",ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

ix tensor([ 611, 7648, 3056, 3583])
inputs:
torch.Size([4, 8])
tensor([[326,   6,  43,  12,  41,  11,   7, 199],
        [ 77,  69, 520,  27,  19, 834, 202,  27],
        [ 42,  10,  78,  16,   3, 754, 363,  19],
        [ 76,  78,  78,   4, 563, 228,  50, 172]])
targets:
torch.Size([4, 8])
tensor([[  6,  43,  12,  41,  11,   7, 199,  15],
        [ 69, 520,  27,  19, 834, 202,  27,  41],
        [ 10,  78,  16,   3, 754, 363,  19, 306],
        [ 78,  78,   4, 563, 228,  50, 172, 418]])
----
when input is [326] the target: 6
when input is [326, 6] the target: 43
when input is [326, 6, 43] the target: 12
when input is [326, 6, 43, 12] the target: 41
when input is [326, 6, 43, 12, 41] the target: 11
when input is [326, 6, 43, 12, 41, 11] the target: 7
when input is [326, 6, 43, 12, 41, 11, 7] the target: 199
when input is [326, 6, 43, 12, 41, 11, 7, 199] the target: 15
when input is [77] the target: 69
when input is [77, 69] the target: 520
when input is [77, 69, 520] the target: 27
whe

In [ ]:
print(xb) # our input to the transformer

tensor([[326,   6,  43,  12,  41,  11,   7, 199],
        [ 77,  69, 520,  27,  19, 834, 202,  27],
        [ 42,  10,  78,  16,   3, 754, 363,  19],
        [ 76,  78,  78,   4, 563, 228,  50, 172]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size): # vocab_size: the number of  all the unique characters
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)  # ！！！ rnn has make incrental input automatically achieve ！！！
        # the 1st is the number of all vocabs needed to be embeded;
        # the 2nd is the dimension of embedding
        # There exist initial weights in nn.Embedding which construct an embedding vector for each vocab

    def forward(self, idx, targets=None): # targets are given for computing loss

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        print("idx",idx)
        print("logits",logits)# embedding results

        #computate loss
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            print(f"B:{B},T:{T},C:{C}")
            logits = logits.view(B*T, C)
            print(f"logits.view:{logits}")
            targets = targets.view(B*T)
            print(f"targets:{targets}")
            loss = F.cross_entropy(logits, targets) # targets element denote position of element 1 in one-hot vector

        return logits, loss

m = BigramLanguageModel(vocab_size)# initialize nn.Embedding
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

#print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


idx tensor([[326,   6,  43,  12,  41,  11,   7, 199],
        [ 77,  69, 520,  27,  19, 834, 202,  27],
        [ 42,  10,  78,  16,   3, 754, 363,  19],
        [ 76,  78,  78,   4, 563, 228,  50, 172]])
logits tensor([[[ 6.6333e-01, -9.5372e-01, -4.4486e-02,  ...,  1.3551e+00,
           4.9192e-01, -1.4185e+00],
         [ 5.4067e-01,  2.4406e-01, -9.5749e-01,  ..., -4.7437e-01,
           8.1878e-01, -1.5438e+00],
         [-7.3893e-01,  1.6159e+00, -3.6602e-02,  ..., -8.3727e-01,
          -3.4574e-01,  9.2198e-01],
         ...,
         [-1.8706e+00,  1.7910e-02, -6.6118e-01,  ...,  1.6273e+00,
          -6.8075e-03,  1.6387e-01],
         [-1.3660e-01, -1.8731e+00,  7.1989e-01,  ..., -2.1054e-01,
          -2.6211e+00,  8.2743e-02],
         [-6.7364e-01, -6.7938e-01,  2.7056e+00,  ..., -9.8645e-01,
          -6.7105e-01,  1.5582e+00]],

        [[-7.4066e-01, -9.5449e-01,  1.3629e+00,  ...,  3.4559e+00,
          -3.9365e-02,  6.6512e-01],
         [-1.3151e-02, -7.4039e-01,  

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size): # vocab_size: the number of  all the unique characters
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for j in range(max_new_tokens): # given only initial promt and then the output/input incrementally generated
            # get the predictions

            logits, loss = self(idx) # go to forward function and loss is not considered
            print(f"idx:{idx},logits:{logits},loss:{loss}")

            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C) where T → 1 (last time step) # the previous steps' outputs have been known
            print(f"logits[:, -1, :]:{logits}")

            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            print(f"probs:{probs}")

            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1) output one character based on the 'probs'
            print(f"idx_next:{idx_next}")

            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

            if j >3:
              break
        return idx

#print(f"xb:{xb},yb:{yb}")
m = BigramLanguageModel(vocab_size)  #with generate function
#logits, loss = m(xb, yb)
#print(logits.shape)
#print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))
# given only initial promt and then the output/input incrementally generated


idx:tensor([[0]]),logits:tensor([[[ 1.8077e-01, -6.9988e-02, -3.5962e-01, -9.1520e-01,  6.2577e-01,
           2.5510e-02,  9.5451e-01,  6.4349e-02,  3.6115e-01,  1.1679e+00,
          -1.3499e+00, -5.1018e-01,  2.3596e-01, -2.3978e-01, -9.2111e-01,
           1.5433e+00,  1.3488e+00, -1.3964e-01,  2.8580e-01,  9.6512e-01,
          -2.0371e+00,  4.9314e-01,  1.4870e+00,  5.9103e-01,  1.2603e-01,
          -1.5627e+00, -1.1601e+00, -3.3484e-01,  4.4777e-01, -8.0164e-01,
           1.5236e+00,  2.5086e+00, -6.6310e-01, -2.5128e-01,  1.0101e+00,
           1.2155e-01,  1.5840e-01,  1.1340e+00, -1.1539e+00, -2.9840e-01,
          -5.0754e-01, -9.2392e-01,  5.4671e-01, -1.4948e+00, -1.2057e+00,
           5.7182e-01, -5.9735e-01, -6.9368e-01,  1.6455e+00, -8.0299e-01,
           1.3514e+00, -2.7592e-01, -1.5108e+00,  2.1048e+00,  2.7630e+00,
          -1.7465e+00,  1.4516e+00, -1.5103e+00,  8.2115e-01, -2.1153e-01,
           7.7890e-01,  1.5333e+00,  1.6097e+00, -4.0323e-01, -8.3447e-01,


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size): # vocab_size: the number of  all the unique characters
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for j in range(max_new_tokens): # given only initial promt and then the output/input incrementally generated
            # get the predictions

            logits, loss = self(idx) # go to forward function and loss is considered currently
            #print(f"idx:{idx},logits:{logits},loss:{loss}")

            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C) where T → 1 (last time step)
            #print(f"logits[:, -1, :]:{logits}")

            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            #print(f"probs:{probs}")

            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1) output one character based on the 'probs'
            #print(f"idx_next:{idx_next}")

            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

            #if j >3:
              #break
        return idx

#print(f"xb:{xb},yb:{yb}")
m = BigramLanguageModel(vocab_size)
#logits, loss = m(xb, yb)
#print(logits.shape)
#print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))
# given only initial promt and then the output/input incrementally generated



性イ伸謡繰作ス睡籠凝盟構付鴉ぬ魚ァ罵元泥画来平習始が語降二物犬待る三太同ル極道逢平迫槌住多軍デず候際ん余騒便規畳妙倍葉吾棄＃執儘面煮皮膏煮ル広　上渡斑稼調弱再刻勇任訳ぜ美壁訪臍忘遠剿口上昔結火女儀袋畳


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

# first use xb yb to train, then use the following m.generate to randomly generate

ix tensor([9127, 6129, 6530, 8320, 9365, 3713, 8172, 3338, 3120, 2889, 7876, 9431,
         264, 9267, 3114, 9468, 7204, 3842, 4486, 8347, 3173, 1284, 5801,  541,
         823, 5578,  505, 2789, 4495, 3060, 7953, 8942])
ix tensor([5096, 6239,  592, 8788, 4488, 2710, 5474, 2869, 3331, 5036, 5042, 4728,
        1315,  437, 1771, 5425, 4825, 4996, 2994, 8847, 4522, 4502,  268, 2870,
        8824, 2019, 7467, 5871,  373, 6485,  997, 7052])
ix tensor([3893, 7099,  281, 8747, 7575, 3874, 3877, 5951, 2750, 9035, 3087, 1959,
        5304,  141, 3487, 3932, 2996, 1050, 6703, 6660, 5624, 8143, 4837,  561,
        4213, 1892, 2222, 6007, 2169, 4765, 1254, 3916])
ix tensor([2600,  142, 3889, 5666, 5806, 5040,  544, 5062, 5062, 3144, 1755, 3445,
        3282, 7450, 3635, 9377, 7296, 6498, 5420, 1482, 3822, 4145, 1099, 8355,
        3333, 6722, 5810, 1415, 1898, 9282,  352, 1773])
ix tensor([6995, 6702, 5716, 1280, 2422, 8006, 7920, 6394,   27, 9276, 3666, 2335,
        5909, 5672, 4952,  752, 3462,

In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


含シ抛判は太向一談へ槌「逢穏較数込欠力習受頭座餓叩尻ニ器便息会こ胃畠両兄内》険惜乱・実黒慨下賞　怒煮百並低家所炬び［桐偉妙論利低双儲もゆ惜満或迫溝偸煮兄的伸愛愛鼓佇む込肝匹デ腹梧師以垂師相拶邸漫も玉盟這ど美火ゼ不喊冷通容苦ょ泣便折年陽除マ居中瀟由鼻観熱増師刺減場拶煙勉杉掠宗付強相朝悪護盛俳づ腹語物漫鼻違腹喟び良層偉な察隣事結立咽イ　枝ぎぐ包疋柄鰡居蔭女調敗洒家筋ゅ尻無冷輝鼻機落迫毒水揄議初嗅えデ月上ぎの袋実飛向智燵鼓左斎［長頃草臭頭質完後珍愛書非残意ゼーめ好善穏輪燵思車風次層師五賞猶強極下様弟聴足打美剿庭層奪永盛上褐現］間渾姿奇困睨読ふ采窃ぎ一的ふ儲さ論待味。失乗側飾禁節鑑助禽奇咽権崩窃偸馬伸王片向生談機嗅耳ァ楽愛遠畜睡間自語猟忘淡聞御同眠底肝炬俳坪軍分驚鳴会暮書行屁馬抛当執際飾御掠体奥向横鼾す屈何火全槌ァ弟隠挫馳稼ド鰡筋タ奴紙化琥ぜ枯怒宿み茂想窘両険炬」渾》廓枝月侮載声含痛頃柔ァ憤定調色動職直体案楽朝声いで語華世も渡何らオな睡給魚戦気身帯業月待ぐげば除サ下任台業蔑飲行最物間悲茶迎亭根ブ弓射点ワ掃任酷切溌め葉方鑑罵案魔用間際矮ほ味睡敬ぬ瀟親ゃ敬玉易飲眺初渡禽ぎ議飛執寝背除ず琥皮偸養泥己


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print('　　　吾　　　輩　　　　は\n','吾\n','輩\n','は\n')
print(a)
print('--')
print('b=')
print('吾\n','輩\n','は\n')
print(b)
print('--')
print('c=')
print(c)

a=
　　　吾　　　輩　　　　は
 吾
 輩
 は

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
吾
 輩
 は

tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape
x

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0) #xbow is the average of the previous t! elements

xbow # it is as same as left-mulitple  a = torch.tril(torch.ones(3, 3))
                                      #a = a / torch.sum(a, 1, keepdim=True)


tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
print("wei",wei)
wei = wei / wei.sum(1, keepdim=True)
print("wei sum",wei)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)
print(xbow2,xbow2)


wei tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei sum tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],


In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
print("tril",tril)
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
print("wei masked_fill ",wei)
wei = F.softmax(wei, dim=-1)
print("wei softmax ",wei)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

wei

tril tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei masked_fill  tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
wei softmax  tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.25

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

print("key",key)
print("query",query)
print("value",value)


k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)　　# B 個 　[T,16] @　　[16, T] それぞれかける

print( "x",x )
print( "k",k )
print( "q",q )
print( "wei",wei )


tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
print( "wei masked_fill",wei )
wei = F.softmax(wei, dim=-1)
print( "wei softmax",wei )

v = value(x)
out = wei @ v
#out = wei @ x
print("v",v)
print("out",out)

out.shape
#print( "x",x )
#print( "k",k )
#print( "q",q )

key Linear(in_features=32, out_features=16, bias=False)
query Linear(in_features=32, out_features=16, bias=False)
value Linear(in_features=32, out_features=16, bias=False)
x tensor([[[ 0.1808, -0.0700, -0.3596,  ..., -0.8016,  1.5236,  2.5086],
         [-0.6631, -0.2513,  1.0101,  ...,  1.5333,  1.6097, -0.4032],
         [-0.8345,  0.5978, -0.0514,  ..., -0.4370, -1.0012, -0.4094],
         ...,
         [-0.8961,  0.0662, -0.0563,  ...,  2.1382,  0.5114,  1.2191],
         [ 0.1910, -0.3425,  1.7955,  ...,  0.3699, -0.5556, -0.3983],
         [-0.5819, -0.2208,  0.0135,  ..., -1.9079, -0.5276,  1.0807]],

        [[ 0.4562, -1.0917, -0.8207,  ...,  0.0512, -0.6576, -2.5729],
         [ 0.0210,  1.0060, -1.2492,  ...,  0.7859, -1.1501,  1.3132],
         [ 2.2007, -0.2195,  0.5427,  ..., -0.6445,  1.0834, -0.7995],
         ...,
         [ 0.3091,  1.1661, -2.1821,  ...,  0.6151,  0.6763,  0.6228],
         [ 0.0943, -0.3156,  0.7850,  ..., -1.5735,  1.3876,  0.7251],
         [ 0.64

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.


In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5
wei

tensor([[[ 1.9857, -1.7370,  0.4189,  0.2985, -0.5451,  0.4942, -0.7267,
          -0.4810],
         [-0.6151,  0.7704,  0.1215,  0.1193, -1.0559, -0.1234,  0.3918,
          -0.2687],
         [ 0.4511,  0.6600,  0.8736, -0.5065,  0.8595,  0.2483,  0.7095,
          -0.3241],
         [ 1.4350, -0.5599,  1.2163, -0.0813,  1.7313,  0.3421, -0.3146,
          -0.9178],
         [-2.0204,  1.8716, -1.1214, -0.1317, -0.4320,  0.8461,  1.0991,
           1.8651],
         [ 1.0000,  0.5394,  0.9807, -0.0900,  0.7364,  1.3018,  1.4779,
           1.2385],
         [ 1.0542, -0.5249,  0.1258, -0.0781,  0.8236, -1.0546,  0.3601,
          -0.5679],
         [ 0.2587,  0.1620,  0.6471,  0.2837,  1.2641,  0.3890, -0.6218,
          -0.4601]],

        [[ 0.2958,  0.3852, -0.7456,  0.0486, -0.1722, -0.3054,  0.8299,
           0.4363],
         [-0.8550,  0.2635,  1.0761,  0.9544,  0.7529, -0.9505,  0.2712,
          -0.7474],
         [-0.9295, -0.1556, -0.0649, -0.3967, -0.1137, -1.0016,  0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
print( torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8,)
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([ 0.8000, -1.6000,  2.4000, -1.6000,  4.0000])


tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)


#!wget https://raw.githubusercontent.com/DING-1994/llm2023/main/icat.txt
with open('icat.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.310091 M parameters
step 0: train loss 6.9366, val loss 6.9089
step 100: train loss 4.6500, val loss 4.8779
step 200: train loss 3.9514, val loss 4.4534
step 300: train loss 3.5006, val loss 4.2476
step 400: train loss 3.2005, val loss 4.2169
step 500: train loss 2.9244, val loss 4.2501
step 600: train loss 2.6884, val loss 4.3490
step 700: train loss 2.4260, val loss 4.3811
step 800: train loss 2.1704, val loss 4.5203
step 900: train loss 1.8574, val loss 4.7124
step 1000: train loss 1.5916, val loss 4.9142
step 1100: train loss 1.3472, val loss 5.1477
step 1200: train loss 1.1115, val loss 5.3431
step 1300: train loss 0.9578, val loss 5.5507
step 1400: train loss 0.7975, val loss 5.8449
step 1500: train loss 0.7027, val loss 6.0773
step 1600: train loss 0.6187, val loss 6.2443
step 1700: train loss 0.5510, val loss 6.3875
step 1800: train loss 0.5111, val loss 6.5195
step 1900: train loss 0.4833, val loss 6.6413
step 2000: train loss 0.4382, val loss 6.7918
step 2100: train loss 0.